#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
GMSH2OOFEM: generates the mesh from Gmsh geometry file and converts it to OOFEM input file.
            (C) 2026 Borek Patzak

The mesh is generated by Gmsh (executable) and exported in UNV format, physical groups
defined in geometry file are exported as UNV groups. The UNV file is converted to oofem
native format by unv2oofem, using ctrl file, see unv2oofem.py for the description of ctrl
file. The properties (cross sections, materials, boundary conditions, loads, sets) are
assigned to mesh components based on the names of physical groups.

Usage: gmsh2oofem.py [options] geofile ctrlfile oofemfile

Options:
  --bgm file.pos     background mesh (Gmsh post-processing view with required element size),
                     when given, the mesh size is controlled by the background mesh only
  --din              write only domain part of oofem file (starting with domain record),
                     as required by oofem domain files (.din) used in adaptive analyses
  --gmsh cmd         Gmsh executable (default gmsh)
  --dim n            mesh dimension (2 or 3, default 2)
  --elemtype type    simplex (default) - triangles/tetrahedra,
                     quad - quadrilaterals (2D), hex - hexahedra (3D);
                     quad/hex meshes are generated by subdivision of simplices
  --order n          element order (default 1)
  --option "opt=val" additional Gmsh option (e.g. "Mesh.Algorithm=6"), can be repeated
  --setnumber n v    set Gmsh geometry parameter n to value v (Gmsh -setnumber, parameter
                     has to be declared using DefineConstant in geometry), can be repeated
  --keep             keep the intermediate files (wrapper geo, unv)

Typical use in oofem adaptive analysis (see GmshInterface):
  adaptlinearstatic ... meshpackage 4 gmshgeo "model.geo" gmshctrl "model.ctrl"
"""
from __future__ import print_function
import argparse
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from unv2oofem import convert


def gmshOptions(args):
    """Returns the list of Gmsh options appended to the geometry"""
    opts = ['Mesh.SaveGroupsOfNodes = 1;', 'Mesh.SaveGroupsOfElements = 1;', 'Mesh.SaveAll = 0;']
    if args.bgm:
        # mesh size given by background mesh only
        opts += ['Mesh.MeshSizeFromPoints = 0;', 'Mesh.MeshSizeExtendFromBoundary = 0;',
                 'Mesh.MeshSizeFromCurvature = 0;']
    if args.elemtype == 'quad':
        # each triangle split into 3 quads -> element size halved, compensated by size factor
        opts += ['Mesh.SubdivisionAlgorithm = 1;', 'Mesh.MeshSizeFactor = 2;']
    elif args.elemtype == 'hex':
        # each tetrahedron split into 4 hexahedra
        opts += ['Mesh.SubdivisionAlgorithm = 2;', 'Mesh.MeshSizeFactor = 2;']
    if args.order > 1:
        opts += ['Mesh.ElementOrder = %d;' % args.order, 'Mesh.SecondOrderIncomplete = 1;']
    for o in args.option:
        opts.append(o if o.rstrip().endswith(';') else o + ';')
    return opts


def main():
    parser = argparse.ArgumentParser(description='Generates mesh by Gmsh and converts it to OOFEM input file.')
    parser.add_argument('geofile')
    parser.add_argument('ctrlfile')
    parser.add_argument('oofemfile')
    parser.add_argument('--bgm', default=None)
    parser.add_argument('--din', action='store_true')
    parser.add_argument('--gmsh', default='gmsh')
    parser.add_argument('--dim', type=int, default=2, choices=[1, 2, 3])
    parser.add_argument('--elemtype', default='simplex', choices=['simplex', 'quad', 'hex'])
    parser.add_argument('--order', type=int, default=1)
    parser.add_argument('--option', action='append', default=[])
    parser.add_argument('--setnumber', nargs=2, action='append', default=[], metavar=('NAME', 'VALUE'))
    parser.add_argument('--keep', action='store_true')
    args = parser.parse_args()

    if args.elemtype == 'hex' and args.dim != 3:
        sys.exit('gmsh2oofem: elemtype hex requires --dim 3')
    if args.elemtype == 'quad' and args.dim != 2:
        sys.exit('gmsh2oofem: elemtype quad requires --dim 2')

    base = os.path.splitext(os.path.abspath(args.oofemfile))[0]
    wrapper = base + '.gmsh.geo'
    unvfile = base + '.unv'

    # wrapper geometry: user geometry + options
    with open(wrapper, 'w') as f:
        f.write('// generated by gmsh2oofem.py\n')
        f.write('Include "%s";\n' % os.path.abspath(args.geofile).replace('\\', '/'))
        for o in gmshOptions(args):
            f.write(o + '\n')

    cmd = [args.gmsh, wrapper, '-%d' % args.dim, '-format', 'unv', '-o', unvfile]
    if args.bgm:
        cmd += ['-bgm', os.path.abspath(args.bgm)]
    for name, value in args.setnumber:
        cmd += ['-setnumber', name, value]
    print('gmsh2oofem: running', ' '.join(cmd))
    sys.stdout.flush()
    if subprocess.call(cmd) != 0:
        sys.exit('gmsh2oofem: gmsh failed')

    convert(unvfile, args.ctrlfile, args.oofemfile, domainOnly=args.din)

    if not args.keep:
        for f in (wrapper, unvfile):
            try:
                os.remove(f)
            except OSError:
                pass


if __name__ == '__main__':
    main()
