// 3D L-shaped beam: L-shaped cross section (in xy plane) extruded in z direction.
// The re-entrant edge at x=y=1 (stress singularity) drives the adaptive refinement.
DefineConstant[ lc = 0.25 ];   // initial (uniform) mesh size, can be changed by gmsh -setnumber lc value
t  = 0.5;    // thickness (extrusion length)

Point(1) = {1.0, 0.0, 0, lc};
Point(2) = {1.5, 0.0, 0, lc};
Point(3) = {1.5, 1.5, 0, lc};
Point(4) = {0.0, 1.5, 0, lc};
Point(5) = {0.0, 1.0, 0, lc};
Point(6) = {1.0, 1.0, 0, lc};   // re-entrant edge

Line(1) = {1, 2};   // bottom face  -> loaded
Line(2) = {2, 3};
Line(3) = {3, 4};
Line(4) = {4, 5};   // left face    -> clamped
Line(5) = {5, 6};
Line(6) = {6, 1};

Curve Loop(1) = {1, 2, 3, 4, 5, 6};
Plane Surface(1) = {1};

// out[0] = top surface, out[1] = volume, out[2..7] = lateral surfaces generated by lines 1..6
out[] = Extrude {0, 0, t} { Surface{1}; };

// Physical groups are exported as UNV groups and referenced from the ctrl file
Physical Volume("Domain") = {out[1]};
Physical Surface("Clamped") = {out[5]};
Physical Surface("Load") = {out[2]};
