/*
 *
 *                 #####    #####   ######  ######  ###   ###
 *               ##   ##  ##   ##  ##      ##      ## ### ##
 *              ##   ##  ##   ##  ####    ####    ##  #  ##
 *             ##   ##  ##   ##  ##      ##      ##     ##
 *            ##   ##  ##   ##  ##      ##      ##     ##
 *            #####    #####   ##      ######  ##     ##
 *
 *
 *             OOFEM : Object Oriented Finite Element Code
 *
 *               Copyright (C) 1993 - 2025   Borek Patzak
 *
 *
 *
 *       Czech Technical University, Faculty of Civil Engineering,
 *   Department of Structural Mechanics, 166 29 Prague, Czech Republic
 *
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */


#ifndef gmshinterface_h
#define gmshinterface_h

#include "mesherinterface.h"
#include "floatarray.h"

#include <string>

///@name Input fields for GmshInterface
//@{
#define _IFT_GmshInterface_geo "gmshgeo"
#define _IFT_GmshInterface_ctrl "gmshctrl"
#define _IFT_GmshInterface_gmshcmd "gmshcmd"
#define _IFT_GmshInterface_pythoncmd "pythoncmd"
#define _IFT_GmshInterface_script "gmsh2oofem"
#define _IFT_GmshInterface_opts "gmshopts"
#define _IFT_GmshInterface_grading "gmshgrading"
//@}

namespace oofem {
/**
 * Interface to the Gmsh mesh generator (https://gmsh.info).
 *
 * The required mesh density is passed to Gmsh as a background mesh: the current mesh is written
 * as a Gmsh post-processing view (.pos file), with the required element size at the nodes
 * (as given by the remeshing criteria). Supported cells are linear (and corner nodes of quadratic)
 * triangles, quads, tetrahedra, hexahedra and wedges, so the background mesh can come
 * from any source (Gmsh itself, other meshers or Subdivision).
 *
 * When the geometry file (gmshgeo) and the unv2oofem control file (gmshctrl) are provided,
 * the new mesh is generated by Gmsh and converted to the oofem domain file by the
 * tools/unv2oofem/gmsh2oofem.py script, and new domain is returned. Additional script options
 * (element type, order, gmsh options) can be passed using gmshopts keyword. Alternatively,
 * any command can be given by remeshcmd keyword (see MesherInterface).
 * Otherwise, only the background mesh file is written (MI_NEEDS_EXTERNAL_ACTION).
 */
class OOFEM_EXPORT GmshInterface : public MesherInterface
{
protected:
    /// Gmsh geometry file.
    std :: string geoFile;
    /// unv2oofem control file.
    std :: string ctrlFile;
    /// Gmsh executable.
    std :: string gmshCmd;
    /// Python interpreter.
    std :: string pythonCmd;
    /// gmsh2oofem conversion script.
    std :: string script;
    /// Additional options passed to gmsh2oofem script (e.g. "--elemtype hex").
    std :: string scriptOpts;
    /**
     * Maximum gradation of the required size field (0 = not limited). When positive, the size at
     * any node is limited by h_j + grading * distance to any other node j, so that the transition
     * from fine to coarse mesh is gradual (e.g. 0.2 - 0.5).
     */
    double grading;

public:
    GmshInterface(Domain * d);
    virtual ~GmshInterface() { }

    returnCode createMesh(TimeStep *tStep, int domainNumber, int domainSerNum, Domain **dNew) override;
    void initializeFrom(const std::shared_ptr<InputRecord> &ir) override;

protected:
    /// Writes the background mesh (Gmsh .pos view with required element sizes).
    int createBackgroundMesh(const std :: string &fileName, TimeStep *tStep);
    /// Limits the gradation of given nodal size field (see grading).
    void limitSizeGradation(FloatArray &h);
};
} // end namespace oofem
#endif // gmshinterface_h
